<?php
/**
 * ChatsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ChatApiCom\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* Whatsapp API documentation
 *
* The REST API allows you to receive and send messages through your WhatsApp account.  Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body. The authorization token is always passed to query string (?token=xxxxxx).  The WhatsApp API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
* OpenAPI spec version: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ChatApiCom\Client;

use ChatApiCom\Client\Configuration;
use ChatApiCom\Client\ApiException;
use ChatApiCom\Client\ObjectSerializer;

/**
 * ChatsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChatApiCom\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChatsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addGroupParticipant
     *
     * Adding a participant to a group.
     *
     */
    public function testAddGroupParticipant()
    {
    }

    /**
     * Test case for creatGroup
     *
     * Creates a group and sends the message to the created group..
     *
     */
    public function testCreatGroup()
    {
    }

    /**
     * Test case for getChats
     *
     * Get the chat list..
     *
     */
    public function testGetChats()
    {
    }

    /**
     * Test case for readChat
     *
     * Open chat for reading messages.
     *
     */
    public function testReadChat()
    {
    }
}
