<?php
/**
 * InstanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ChatApiCom\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* Whatsapp API documentation
 *
* The REST API allows you to receive and send messages through your WhatsApp account.  Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body. The authorization token is always passed to query string (?token=xxxxxx).  The WhatsApp API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
* OpenAPI spec version: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ChatApiCom\Client;

use ChatApiCom\Client\Configuration;
use ChatApiCom\Client\ApiException;
use ChatApiCom\Client\ObjectSerializer;

/**
 * InstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChatApiCom\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getQRCode
     *
     * Direct link to QR-code in the form of an image, not base64..
     *
     */
    public function testGetQRCode()
    {
    }

    /**
     * Test case for getSettings
     *
     * Get settings.
     *
     */
    public function testGetSettings()
    {
    }

    /**
     * Test case for getStatus
     *
     * Get the account status and QR code for authorization..
     *
     */
    public function testGetStatus()
    {
    }

    /**
     * Test case for logout
     *
     * Logout from WhatsApp Web to get new QR code..
     *
     */
    public function testLogout()
    {
    }

    /**
     * Test case for reboot
     *
     * Logout from WhatsApp Web to get new QR code..
     *
     */
    public function testReboot()
    {
    }

    /**
     * Test case for setSettings
     *
     * Set settings.
     *
     */
    public function testSetSettings()
    {
    }
}
