<?php
/**
 * MessagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ChatApiCom\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* Whatsapp API documentation
 *
* The REST API allows you to receive and send messages through your WhatsApp account.  Parameters in GET queries pass query string. Parameters in POST requests — through the JSON-encoded request body. The authorization token is always passed to query string (?token=xxxxxx).  The WhatsApp API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
* OpenAPI spec version: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ChatApiCom\Client;

use ChatApiCom\Client\Configuration;
use ChatApiCom\Client\ApiException;
use ChatApiCom\Client\ObjectSerializer;

/**
 * MessagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChatApiCom\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for forwardMessage
     *
     * Forwarding messages to a new or existing chat..
     *
     */
    public function testForwardMessage()
    {
    }

    /**
     * Test case for getMessages
     *
     * Get a list of messages..
     *
     */
    public function testGetMessages()
    {
    }

    /**
     * Test case for sendContact
     *
     * Sending a contact or contact list to a new or existing chat..
     *
     */
    public function testSendContact()
    {
    }

    /**
     * Test case for sendFile
     *
     * Send a file to a new or existing chat..
     *
     */
    public function testSendFile()
    {
    }

    /**
     * Test case for sendLink
     *
     * Send text with link and link's preview to a new or existing chat..
     *
     */
    public function testSendLink()
    {
    }

    /**
     * Test case for sendLocation
     *
     * Sending a location to a new or existing chat..
     *
     */
    public function testSendLocation()
    {
    }

    /**
     * Test case for sendMessage
     *
     * Send a message to a new or existing chat..
     *
     */
    public function testSendMessage()
    {
    }

    /**
     * Test case for sendPTT
     *
     * Send a ptt-audio to a new or existing chat..
     *
     */
    public function testSendPTT()
    {
    }

    /**
     * Test case for setWebhook
     *
     * Sets the URL for receiving webhook notifications of new messages and message delivery events (ack)..
     *
     */
    public function testSetWebhook()
    {
    }
}
